skill4j.llm.host=http://localhost:11434
skill4j.llm.request.model-name=phi4-mini:3.8b-q4_K_M
skill4j.llm.request.timeout-secs=200
skill4j.llm.request.system-prompt=${file:hello.system-prompt}

skill4j.llm.options.topK=40
skill4j.llm.options.topP=0.9
skill4j.llm.options.temperature=0.7
skill4j.llm.options.repeatPenalty=1.1
skill4j.llm.options.seed=42